"""The two identifiers a tagged spool carries, which are not alternatives.

**The silicon UID** is assigned at the factory and cannot be changed. The chips
in use acknowledge writes to the UID pages and silently discard them, so it is
read-only in practice and no attempt is made to write one. It is what a printer
reports when a tag is presented, and it lives in Spoolman's ``card_uids``.

**The serial** is generated by software, written into the tag's payload, and is
what the SpoolFlex and OpenSpool ecosystem calls ``spool_id``. It is Unix time
in microseconds — confirmed by decoding a real SpoolFlex value, which resolved
to the moment that tag was written. Microseconds give a value that is unique
without a counter or a database round trip, is monotonic, and renders in
exactly sixteen digits, which is the width of OpenTag3D's serial field.

Both are written. Conflating them was the longest wrong turn in this project.
"""

import threading
import time
from datetime import datetime, timezone

SERIAL_DIGITS = 16
_MICROSECONDS = 1_000_000

_lock = threading.Lock()
_last = 0


def normalise_uid(uid: bytes | bytearray | str) -> str:
    """Render a UID the way printers report it: uppercase hex, no separators.

    A Snapmaker displays ``04:BB:14:57:D3:2A:81`` and reports
    ``04BB1457D32A81``; both have to compare equal to what is stored.

    Args:
        uid: Raw UID bytes, or a string that may carry colons, dashes or spaces.

    Returns:
        str: The normalised UID.

    """
    if isinstance(uid, (bytes, bytearray)):
        return "".join(f"{byte:02X}" for byte in uid)
    return "".join(str(uid).split()).replace(":", "").replace("-", "").upper()


def generate_serial() -> str:
    """Generate a fresh serial, strictly increasing within this process.

    Returns:
        str: Sixteen digits of microsecond Unix time.

    """
    global _last  # noqa: PLW0603 - one counter, guarded, for the life of the process
    with _lock:
        now = int(time.time() * _MICROSECONDS)
        if now <= _last:
            now = _last + 1
        _last = now
    return str(now)


def serial_to_datetime(serial: str | int) -> datetime | None:
    """Recover the moment a serial was generated, for display.

    Args:
        serial: A serial as read from a tag.

    Returns:
        datetime | None: When it was generated, or None if it is not one of ours.

    """
    try:
        return datetime.fromtimestamp(int(serial) / _MICROSECONDS, tz=timezone.utc)
    except (ValueError, TypeError, OSError, OverflowError):
        return None
